- name: ec2-ssh-check
  hosts: localhost
  gather_facts: false
  connection : local

  tasks:
    - name: Wait for ssh to come up
      wait_for: host="ec2-18-222-186-37.us-east-2.compute.amazonaws.com" port=22 delay=10  timeout=300
      register: ssh_out

    - debug:
        var: ssh_out